name: nbteditor
description: A Minecraft NBT Editor written in Flutter
publish_to: 'none'
version: 1.0722.24+1506


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  flutter_treeview: ^1.0.7+1
  libac_dart:
    hosted: https://git.zontreck.com/api/packages/AriasCreations/pub/
    version: 1.2.072224+0449

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - "Icons/PNG/Boolean.png"
    - "Icons/PNG/Byte.png"
    - "Icons/PNG/ByteArray.png"
    - "Icons/PNG/Compound.png"
    - "Icons/PNG/Double.png"
    - "Icons/PNG/Float.png"
    - "Icons/PNG/Int.png"
    - "Icons/PNG/IntArray.png"
    - "Icons/PNG/List.png"
    - "Icons/PNG/Long.png"
    - "Icons/PNG/LongArray.png"
    - "Icons/PNG/Short.png"
    - "Icons/PNG/String.png"
    - "Icons/PNG/AppLogo.png"
    - "Icons/PNG/AppLogo-sweet.png"