name: nbteditor
description: A Minecraft NBT Editor written in Flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_treeview: ^1.0.7+1
  libac_dart:
    hosted: https://git.zontreck.com/api/packages/AriasCreations/pub/
    version: 1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
