name: nbteditor
description: A Minecraft NBT Editor written in Flutter
publish_to: 'none'
version: 0.070224.2238


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  flutter_treeview: ^1.0.7+1
  libac_dart:
    hosted: https://git.zontreck.com/api/packages/AriasCreations/pub/
    version: 1.1.070224+2232

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
