name: nbteditor
description: A Minecraft NBT Editor written in Flutter
publish_to: "none"
version: 1.1.030625+0131

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.2
  libac_dart:
    hosted: https://git.zontreck.com/api/packages/Packages/pub/
    version: ^1.4.020325+1215
  cupertino_icons: ^1.0.8
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_treeview:
    hosted: https://git.zontreck.com/api/packages/Packages/pub/
    version: ^1.2.020525+0254
  permission_handler: ^11.3.1
  libacflutter:
    hosted: https://git.zontreck.com/api/packages/Packages/pub/
    version: ^1.0.031525+0222
  file_selector: ^1.0.3

  flutter_highlight: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "Icons/PNG/Boolean.png"
    - "Icons/PNG/Byte.png"
    - "Icons/PNG/ByteArray.png"
    - "Icons/PNG/Compound.png"
    - "Icons/PNG/Double.png"
    - "Icons/PNG/Float.png"
    - "Icons/PNG/Int.png"
    - "Icons/PNG/IntArray.png"
    - "Icons/PNG/List.png"
    - "Icons/PNG/Long.png"
    - "Icons/PNG/LongArray.png"
    - "Icons/PNG/Short.png"
    - "Icons/PNG/String.png"
    - "Icons/PNG/nbteditor.png"
    - "Icons/PNG/nbteditor-sweet.png"
